title: Viki's Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: alittleredpanda #if your site has a twitter account, enter it here

# Author Settings
author: Viki Johnson # add your name
author-img: profilepic.png # add your photo
about-author: Hey, I'm a programmer, developer and illustrator. I love making games and other lovely digital things. I'm slowly adding all posts from my old tumblr blogs... # add description
social-twitter: alittleredpanda # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: viki-johnson # add your Github handle
social-linkedin: viki-johnson # add your Linkedin handle
social-email: alittleredpanda@gmail.com# add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
